// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: treaty.proto

package treaty

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ServerType int32

const (
	ServerType_SNone     ServerType = 0
	ServerType_Balancer  ServerType = 1 //gate server
	ServerType_Connector ServerType = 2 //connector server
	ServerType_Game      ServerType = 3 //game server
)

// Enum value maps for ServerType.
var (
	ServerType_name = map[int32]string{
		0: "SNone",
		1: "Balancer",
		2: "Connector",
		3: "Game",
	}
	ServerType_value = map[string]int32{
		"SNone":     0,
		"Balancer":  1,
		"Connector": 2,
		"Game":      3,
	}
)

func (x ServerType) Enum() *ServerType {
	p := new(ServerType)
	*p = x
	return p
}

func (x ServerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerType) Descriptor() protoreflect.EnumDescriptor {
	return file_treaty_proto_enumTypes[0].Descriptor()
}

func (ServerType) Type() protoreflect.EnumType {
	return &file_treaty_proto_enumTypes[0]
}

func (x ServerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerType.Descriptor instead.
func (ServerType) EnumDescriptor() ([]byte, []int) {
	return file_treaty_proto_rawDescGZIP(), []int{0}
}

type Server struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerId   int32      `protobuf:"varint,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerType ServerType `protobuf:"varint,2,opt,name=server_type,json=serverType,proto3,enum=treaty.ServerType" json:"server_type,omitempty"`
	ServerName string     `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ServerHost string     `protobuf:"bytes,4,opt,name=server_host,json=serverHost,proto3" json:"server_host,omitempty"`
}

func (x *Server) Reset() {
	*x = Server{}
	if protoimpl.UnsafeEnabled {
		mi := &file_treaty_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_treaty_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_treaty_proto_rawDescGZIP(), []int{0}
}

func (x *Server) GetServerId() int32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *Server) GetServerType() ServerType {
	if x != nil {
		return x.ServerType
	}
	return ServerType_SNone
}

func (x *Server) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Server) GetServerHost() string {
	if x != nil {
		return x.ServerHost
	}
	return ""
}

var File_treaty_proto protoreflect.FileDescriptor

var file_treaty_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x72, 0x65, 0x61, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x74, 0x72, 0x65, 0x61, 0x74, 0x79, 0x22, 0x9c, 0x01, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x33,
	0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x74, 0x72, 0x65, 0x61, 0x74, 0x79, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x68,
	0x6f, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x48, 0x6f, 0x73, 0x74, 0x2a, 0x3e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0c,
	0x0a, 0x08, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x47,
	0x61, 0x6d, 0x65, 0x10, 0x03, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x74, 0x72, 0x65, 0x61, 0x74,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_treaty_proto_rawDescOnce sync.Once
	file_treaty_proto_rawDescData = file_treaty_proto_rawDesc
)

func file_treaty_proto_rawDescGZIP() []byte {
	file_treaty_proto_rawDescOnce.Do(func() {
		file_treaty_proto_rawDescData = protoimpl.X.CompressGZIP(file_treaty_proto_rawDescData)
	})
	return file_treaty_proto_rawDescData
}

var file_treaty_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_treaty_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_treaty_proto_goTypes = []interface{}{
	(ServerType)(0), // 0: treaty.ServerType
	(*Server)(nil),  // 1: treaty.Server
}
var file_treaty_proto_depIdxs = []int32{
	0, // 0: treaty.Server.server_type:type_name -> treaty.ServerType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_treaty_proto_init() }
func file_treaty_proto_init() {
	if File_treaty_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_treaty_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Server); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_treaty_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_treaty_proto_goTypes,
		DependencyIndexes: file_treaty_proto_depIdxs,
		EnumInfos:         file_treaty_proto_enumTypes,
		MessageInfos:      file_treaty_proto_msgTypes,
	}.Build()
	File_treaty_proto = out.File
	file_treaty_proto_rawDesc = nil
	file_treaty_proto_goTypes = nil
	file_treaty_proto_depIdxs = nil
}
